<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.ServiceBus" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CartService.Api\CartService.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\infra\servicebus-emulator\Config.json" Link="ServiceBus\Config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
