<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CartService.Application\CartService.Application.csproj" />
    <ProjectReference Include="..\CartService.Domain\CartService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CartService.Api.IntegrationTests" />
  </ItemGroup>

</Project>
